---
name: Bionic Barnacle
description: |
  Bionic Barnacle is a fan for the fan showdown on youtube. 
  It is based from [this video](https://www.youtube.com/watch?v=WezeLNC32sA)

  ## Theory
  Blue whales have bone like structures at the front of their fins which channel the fluid
  The channels increase the stall speed. They also reduce cavitation and noise. 

  [video explination](https://youtube.com/clip/UgkxG9djbZuyymOV0Q9jzOuuVxhViXQogz-p?si=p6os4688hcQDM0JV)

  ## Design

  version 1.0 is a prototype with no engineering into blad angle. There is likely much improvment that could be made. 

license: 
  type: CC-Attribution # MIT, GPL, CC-Attribution, CC-Attribution-NoDerivs, CC-Attribution-ShareAlike, CC-Attribution-NonCommercial, CC-Attribution-NC-SA
  owner: Spencer Owen
  year: 2023
resources:
  # foo: https://example.com
# fusion_link: https://autodesk.example.com #comment out if no fusion link
# links:
#   Thingiverse: https://www.thingiverse.com/thing:xxxx
#   Printables: https://foo.com
#   GrabCad: https://foo.com
#   Hackster.io: https://hackster.io/foo
#   Hackaday: https://hackaday.io/foo
#   Reddit: https://www.reddit.com/r/foo
#   Github: https://github.com/foo
#   Blog: https://foo.com
