---
name: Bionic Barnacle
description: |
  Bionic Barnacle is a fan for [the fan showdown on youtube](https://www.youtube.com/@MajorHardware). 
  It is based from [this video](https://www.youtube.com/watch?v=WezeLNC32sA)

  Remixed from [bionic propeller](https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbDlQOWV3MlRJUWs5NHY0c2k5OFRDSzFTTUxid3xBQ3Jtc0tsNko2YWh0VHR2dUwyLWRNTmdCaWJULVF2UFVlSDF3ZEV2dXlqRC1wemwwLWh0d0lObGFDRlNDQXR3eUtmVS05c3RGZTU3RWNabU5EMVpHazA1akVjZTByWlEyeHppUkVKcHQ3QVFCMXhreWRScndKSQ&q=https%3A%2F%2Fgrabcad.com%2Flibrary%2Fbiomimetic-marine-propeller-1&v=WezeLNC32sA)

  ## Theory
  Blue whales have bone like structures at the front of their fins which act as channels or funnels. 
  The funneled water travels faster over the top of the fin which in turn increases stall speed. They also reduce cavitation and noise. 

  [video explination of tubicle effect ](https://youtube.com/clip/UgkxG9djbZuyymOV0Q9jzOuuVxhViXQogz-p?si=-x8lITLNDP_PUeTi)

  ## Design

  version 1.0 is a prototype with no engineering into blad angle. There is likely much improvment that could be made. 

license: 
  type: CC-Attribution # MIT, GPL, CC-Attribution, CC-Attribution-NoDerivs, CC-Attribution-ShareAlike, CC-Attribution-NonCommercial, CC-Attribution-NC-SA
  owner: Spencer Owen
  year: 2023
resources:
  # foo: https://example.com
# fusion_link: https://autodesk.example.com #comment out if no fusion link
# links:
#   Thingiverse: https://www.thingiverse.com/thing:xxxx
#   Printables: https://foo.com
#   GrabCad: https://foo.com
#   Hackster.io: https://hackster.io/foo
#   Hackaday: https://hackaday.io/foo
#   Reddit: https://www.reddit.com/r/foo
#   Github: https://github.com/foo
#   Blog: https://foo.com
